### ISSUE TITLE
Add Foundation datepicker to date inputs

### ISSUE THREAD

**Issue by htmlboy** [decidim/design-admin#8]
#### :tophat: User Story
Date inputs are non consistent. We need a proper plugin.

#### :clipboard: Related documentation
http://foundation-datepicker.peterbeno.com

#### :dart: Acceptance criteria
Customs date inputs work well with mouse, keyboard and touch.

**Comment by htmlboy** [comment]
@josepjaume could you confirm http://foundation-datepicker.peterbeno.com is the right date picker?

**Comment by josepjaume** [comment]
That's it! Could you style it both for `decidim-admin` and `decidim`? I'm perfectly OK with just copying styles :)

**Comment by htmlboy** [comment]
Sure. If you want to open a new issue in decidim-design…
